---
title: "Milwaukee is shrinking. Nashville and Minneapolis growing. Immigrants help them thrive."
date: "November 16, 2023"
author: "Mike Gousha and John Johnson"
---

A small woman with a warm smile and wry sense of humor, 46-year-old Nang Kham arrived in Milwaukee more than a decade ago, a refugee from a place halfway around the world. Kham was born in Burma, the southeast Asian country also known as Myanmar. The daughter of a Burmese politician and a nurse, political turmoil in her country had forced her family to flee to a refugee camp on the border between Burma and Thailand.

“We lived in a tent,” Kham recalled. Food was rationed and water was scarce. Travel outside the camp was not allowed. No one had a job.

Kham applied for refugee status and in 2007 she was allowed to come to the United States. She initially settled in southern California. Her parents remained behind to help others at the refugee camp.

“I came here alone,” Kham told us. “It was scary.”  

After living in California for three years, she moved to Milwaukee in 2010. Her brother, also a refugee, had moved here the year before. Three months after her arrival, Kham had her first job, making sandwiches at Subway. Kham chuckled as she remembered that time. “I don’t know, what is salami, what is pepperoni?”

But unlike many of her fellow refugees, Kham spoke English as well as two different languages common in Burma. She began working as an interpreter, and then spent six years at Neighborhood House as a bilingual assistant.

Today, she is a realtor. Because of her language skills, the close-knit Burmese community asked her to get a real estate license, so she could help the newcomers become homeowners. Kham agreed, eager to make a difference. She said Milwaukee’s Burmese community is growing, attracting even those who first settled in other American cities.

“The first thing is, it’s easier to find a job, to get around town, go shopping, go to work,” Kham explained. She said she is much happier in Milwaukee than she was in California.

“I think Milwaukee is the best, compared to the other states.”

## Share of immigrant population in Milwaukee lagging

Milwaukee’s history with immigration is long and rich. The 1850 census— the first after Wisconsin achieved statehood— found that 55% of the population was born outside the U.S. While America was still a young country at the time, Milwaukee’s experience was hardly the norm. Nationwide, about 10% of residents were foreign born.

Today, the census estimates that roughly 119,000 immigrants live in the four-county Milwaukee metropolitan area, and there are 47,000 kids being raised by at least one immigrant parent. The number of Milwaukee area residents born outside the country is now double that of 1980.

But those facts overshadow another important truth, one with major implications for our region. The share of the immigrant population in metro Milwaukee is now barely half that of the nation. In 2022, about 14% of Americans were born outside the U.S., compared to fewer than 8% of those living in our area. And that raises an important question; could attracting more immigrants help address two of our region’s serious challenges: stagnant population growth and a rapidly aging workforce?

At first glance, this may not seem like the right time for a conversation about greater immigration in metro Milwaukee. Social services in some cities, including Chicago and New York, are currently overwhelmed by record numbers of asylum seekers arriving from the southern border. On Capitol Hill, comprehensive immigration reform remains a pipedream.

Given that backdrop, it is important to clarify the sources of immigration. Asylum seekers mostly arrive in the country without existing connections, and they are generally prevented by federal law from working for at least six months after filing their applications. As Chicago’s experience shows, resolving this situation will require concerted federal action. Cities cannot go it alone.

Still, most immigrants arrive through more standard forms of legal immigration, which is largely based on family relationships and targeted work skills. Another common source, especially in Milwaukee, is refugee resettlement where vetted individuals and families are already paired with support from community groups before arriving. These forms of legal immigration present a potential opportunity for Milwaukee. Immigration totals in the U.S. are climbing again. The census estimates that last year the number of people born outside the U.S. grew by nearly 1 million to more than 46 million.

The Wall Street Journal reported recently that the historic rise in immigration is the result of the U.S. catching up on a backlog of visa applications and the Biden administration accelerating work permits. The result, the paper noted, has been a boost to the U.S. economy, as labor shortages and wage and price pressures ease.

The newcomers—the majority of whom are here legally—work in a wide range of jobs: in restaurants and hotels, on production lines and dairy farms, in the technology sector, and on university campuses. While many begin their lives in America in big cities like New York, Chicago, and Houston, they often migrate to mid-sized cities and their suburbs. Should Milwaukee be one of them?

## Where do immigrants hail from? Answer might surprise you.

Most immigrants arrived in metro Milwaukee in two waves: before the 1920s and after the 1960s. The 40-year gap in significant immigration was largely the result of federal legislation that sharply curtailed the number of people allowed into the country.

Immigration here reached its peak in the 1880s, fueling the city’s rapid population growth. By 1910, Milwaukee had become the 12th largest American city (we are now 31st), a place known for its industrial and political innovation. Approximately six out of every 1,000 American residents lived in the area. In contrast, roughly 11 out of every 1,000 foreign-born residents in the U.S. lived here.

But the city did not remain a magnet for immigrants. After 1970, immigration to the U.S. began to soar, but not in metro Milwaukee, where the share of the foreign-born population fell to less than 4% in 1990, an all-time low. Since then, the immigrant share of metro Milwaukee’s population has risen steadily but remains less than cities like Columbus, Ohio, Rockford, Illinois, and Des Moines, Iowa.

The face of immigration in metro Milwaukee has changed considerably over time. In its first century, the newcomers were largely from Europe, with German and Polish immigrants leading the way. In 1900, fully 64% of immigrants living in the metro hailed from Germany, followed by 15% from Poland.

Today, immigrants come from around the world. Mexico provides the largest share at 31%. Those 36,000 Mexican immigrants are joined by about 2,600 from Central American nations, 3,900 from South America, and 3,000 from the Caribbean. All told, about 46,000 Milwaukee metro residents are from Latin America — 39% of all immigrants. These statistics do not include Puerto Ricans, because they are not foreign-born. It is worth noting that the same census data estimates 15,000 current metro Milwaukee residents were born in Puerto Rico.

Latin Americans may make up the largest group of immigrants to Milwaukee, but the Latin American immigrant population share is still less than half the national average.

The other primary source of immigrants to our area is Asia. Most come from the south central or southeastern parts of the continent. They constitute 38% of immigrants to metro Milwaukee, or an estimated 44,000 residents.

The largest number of Asian immigrants were born in India, about 12,700 residents. They represent 11% of the metro’s total immigrant population.

Metro Milwaukee is also home to 5,900 Chinese immigrants. But the Chinese-born population here is far below the national average, while the percentage of Indian immigrants in metro Milwaukee is similar to the national average.

While their numbers are smaller, four southeast Asian countries —Burma or Myanmar, Laos, Malaysia, and Thailand — contribute far more immigrants to the Milwaukee metro than is typically found in the rest of the U.S.

Well over a century ago, Europeans flocked to Milwaukee in large numbers. Today, 16% of the immigrants in the area, or approximately 19,000, were born in a European country. They come mainly from Eastern Europe, but in a nod to Milwaukee’s past, the largest single source of European immigrants is still Germany. About 3,400 German-born residents live here.

Only about 6% of area immigrants, or roughly 6,600 residents, are from African nations. Milwaukee’s share of African immigrants is about 44% smaller than the national average.

Even though metro Milwaukee lags the nation in terms of overall immigration, the metro has held its own when it comes to refugee settlement, with the pace picking up during the past decade. During the 1990s, refugees most often came from the former Soviet Union and Yugoslavia. More recently, the most common country of origin has been Burma, or Myanmar. By 2018, the metro had resettled about 5,300 refugees from Burma. The peak year was 2016, when more than 1,400 refugees arrived.

## Cities with strong economies have growing immigrant populations

Why do these numbers matter, especially in a place like Milwaukee?

A 2021 analysis produced by the Brookings Institution noted that “cities with the fastest growing immigrant populations over the period 2010-2019 were all medium-sized cities with thriving economies, led by Charleston, South Carolina, Des Moines, Iowa, Louisville, Kentucky, Columbus, Ohio, and Nashville, Tennessee.”

In many of these cases, the analysis stated, “immigrants reversed long-standing population declines. More important, immigrants’ high rates of entrepreneurship and labor force participation helped boost local economies that had been stagnant for decades.”

A 2022 study published by the George W. Bush Institute at Southern Methodist University found that metros and counties with relatively large immigrant population shares performed better in household income, innovation, overall productivity, and startup businesses.  “Cities that succeed best in attracting newcomers — immigrant and native-born alike—and creating conditions for them to thrive will likely achieve outsized prosperity in coming decades, as they have always done,” the report concluded.

There is no secret sauce to population growth. Metros grow in one of three ways. They have more births than deaths. More Americans move to a place than away from it, or what is called domestic migration. And finally, there is international immigration.

From 2010-2019, immigration accounted for 44% of Wisconsin’s population growth. Nearly half of the immigrants moved to metro Milwaukee. And yet, the four-county area’s population only grew by about 19,000 residents over the past decade.

Our sluggish population growth has been the result of declining birthrates and people leaving. In fact, without the influx of immigrants, the metro’s population would have shrunk considerably, with serious implications for the region’s economy.

To our northwest, immigrants are playing an increasing role in the Minneapolis metro and Minnesota economies, which face some of the same workforce challenges seen in Milwaukee and Wisconsin. Recent census data now estimates that 11% of the residents in the Minneapolis metro are foreign-born, or 399,000 people. Again, in Milwaukee, 8% were born outside the U.S. If immigrants came to the Milwaukee metro in the same proportion as they do Minneapolis, our population would be 55,000 larger. Keep in mind, the rate of immigration in the Minneapolis metro is still less than the national average.

The Minnesota Department of Employment and Economic Development highlighted the importance of the region’s newcomers to the area’s economy in a recent report. “Wherever they work,” the report concluded, “these new Minnesotans are a vital part of the state and region’s economy, providing rapid growth to an otherwise aging and slowing labor force. “

Several factors, including economic opportunity, existing immigrant communities, housing costs, and good schools, play a role in where immigrants choose to live. But so does public policy, which can make a metro more welcoming to new arrivals. For example, the city of Minneapolis has created an office for immigrants and refugee affairs to help make immigrants’ transition to their new home smoother.

Buffalo offers another example of intentional outreach. In 2015, Buffalo launched the Office of New Americans to serve its growing refugee and immigrant communities. According to the city’s website, the office’s mission is “to promote access to city services, area resources and to implement policies that facilitate the successful integration of newcomers into the civic, economic, and cultural life of Buffalo.”

What does that mission look like in practice? In September, Buffalo’s mayor announced a program to reduce language barriers for new arrivals, with city communications in the six most common languages spoken in Buffalo, besides English: Spanish, Arabic, Bengali, Burmese, Karen, and Swahili.

There have been efforts to do something similar in Milwaukee. In 2021, the city requested bids to create the Milwaukee Immigrant and Refugee Welcome Center.  “It was evident that there is no single point of access to services for new arrivals to get information on services available, “the request explained. “Even when newcomers know about different services available, connecting them can be difficult, due to barriers such as language, transportation and childcare.”

Two years later, the welcome center has yet to materialize. But in response to a question, Mayor Cavalier Johnson said the city remains interested in developing one, with support from private sector partners.

Using a variety of metrics, the Bush Institute report ranked cities where immigrants were “thriving best.”  Some of the places where foreign-born residents were faring well were not surprising. They included tech hubs like San Jose, San Francisco, and Seattle. But the report found that immigrants also thrived in metros like Baltimore, St. Louis, Pittsburgh, and Cincinnati and noted that a number of the cities had enacted explicit welcoming policies for immigrants. Metro Milwaukee finished in the middle of the 100 metros that were ranked.

Recent census data puts the median income of an immigrant household in Wisconsin at about 94% that of native-born households. Outcomes tend to improve the longer immigrants live here. For instance, when Hmong refugees began arriving in Wisconsin in the 1970s and 1980s, many were poor. In 1990, the average Hmong immigrant’s household income was just 39% of the state average. Our analysis of the most recent census data found that the median household income for Hmong immigrants now exceeds the state average.

Mayor Johnson, who has set has set an ambitious goal for population growth, called Milwaukee a welcoming community for immigrants, with the city’s block grant agency investing in church and community agency efforts to help those who settle here. He also said the city needs more immigrants to grow its population and economy.

“Ultimately, Milwaukee welcomes immigrants who are looking to make their lives here, who want their families to grow here, and who want to be hardworking additions to our local economy,” Johnson said. “That is a tradition that has served Milwaukee well for more than 175 years.”

Johnson said Milwaukee has largely avoided the rancorous debates over asylum seekers and said it is up to states and federal governments to create “sensible and reasonable” policies to address the issue.

In today’s highly charged political environment, even having a conversation about greater immigration is likely to produce opposition. Our metro has pockets of deep poverty and there are serious resource questions that would need to be answered. It is also possible that more restrictive immigration policies could return depending on future election outcomes.

But the public still views immigration in a favorable light. In a national Gallup poll conducted in June of this year, 68% of those surveyed said that immigration is a good thing for the country today. Just 27% said it was a bad thing.

Talk to an immigrant family, and you often hear of the struggle. The challenge of finding adequate housing. Of learning a new language. Of adapting to a new culture. Nang Kham described the transition of her fellow Burmese refugees, as “very hard.”

Still, she said most in her community have found jobs. They are buying houses and, like Kham, becoming U.S. citizens. Kham even helped her community purchase two churches so they would have places to worship, one at 24th and State in Milwaukee and another in Brown Deer.

Kham smiled wistfully as she talked about her former home, Burma, or Myanmar. She said she still thinks about it often. But just like the Germans and Poles who came before her, she has built a new life in Milwaukee.

“To be an American dream,” she said, “you have to risk a lot."
