project:
  type: website
  output-dir: docs

website:
  title: "John Johnson's Internet Archive"
  navbar:
    search: true
    left:
      - text: "Table of Contents"
        href: index.qmd
      - text: "External Links"
        href: external-links.qmd
      - text: "Blue Book Newsletter"
        href: https://bluebookmke.substack.com/
        target: _blank
      - about.qmd
  google-analytics: "G-31XDQG3G4L"

lightbox: true

format:
  html:
    theme: 
      - litera
      - custom.scss
    backgroundcolor: "linen"
    mainfont: "Iowan Old Style"
    linkcolor: "black"
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'

execute:
  freeze: auto

