---
title: "Historic Maps of Milwaukee on an Interactive Map"
author: "John Johnson"
date: "April 29, 2025"
---

This interactive tool allows you to toggle between 5 different maps of Milwaukee from different points in its history. Much changes between them. Two of the most dramatic changes to explore are the demolition of many neighborhoods to create freeways and the creation of much of the modern-day lakefront via infill.

* the first map shows 2025 data from OpenStreetMap (specifically the [CARTO Voyager](https://github.com/CartoDB/basemap-styles) basemap)
* the [1958 map](https://collections.lib.uwm.edu/digital/collection/agdm/id/35686) was made by the US Geological Survey based off aerial imagery collected in the 1950s. It shows Milwaukee just before the construction of the modern freeway system.
* the [1934 map](https://collections.lib.uwm.edu/digital/collection/agdm/id/5849/rec/63) was drawn by "J.L.W." of the Milwaukee City Engineer's Department.
* the [1897 map](https://collections.lib.uwm.edu/digital/collection/agdm/id/36039/rec/57) was drawn by Willmanns Bros Litho to show the locations of completed sewers as of December 31st, 1897.
* the [1856 map](https://collections.lib.uwm.edu/digital/collection/agdm/id/44/rec/80) was drawn by [Increase Lapham](https://www.wisconsinhistory.org/Records/Article/CS527). Milwaukee had been incorporated just 10 years prior, so the area shown by this map is much smaller than that of subsequent maps.

:::{.column-page}
```{=html}
<iframe width="100%" height="800" src="post-assets/milwaukee-old-maps-leaflet.html", title="Interactive Maps"></iframe>
```
:::

I obtained digitized versions of these maps from the [American Geographical Society Library Digital Map Collection](https://uwm.edu/lib-collections/agsl-digital-map-collection/) at the UWM Library. I used the remarkable free tool [AllMaps.org](https://allmaps.org/) to georeference the files. AllMaps turns the georeferenced files into tiles, which I serve using a leaflet map above.