---
title: "Milwaukee lagging its Midwestern peers in a key metric of economic vitality: population growth"
date: "May 28, 2020"
author: "Mike Gousha and John Johnson"
---

*This article [originally appeared](https://www.jsonline.com/story/news/solutions/2020/05/28/milwaukee-lags-midwestern-cities-key-metric-population-growth/5262045002/) in the Milwaukee Journal Sentinel.*

The novel coronavirus changed life in metropolitan Milwaukee. For weeks, streets and shopping malls were eerily quiet. Hotels and office towers were mostly empty. The Democratic National Convention, Milwaukee’s chance to strut its stuff before a national audience, was moved from July to August in hopes that the health crisis would ease and at least some version of the convention could be held.

For civic boosters, landing the Democratic convention was proof that Milwaukee was a city on the rise. Before the virus hit, they saw a metropolitan area growing in vitality and confidence. But buried beneath the COVID-19 headlines was a recent release from the U.S. Census Bureau that points to a key type of growth missing from our comeback story, something metro Milwaukee will have to contend with after the virus passes.

The official 2020 census count is still underway, but Census Bureau population estimates show that in the last decade, thousands of metro Milwaukee residents have left the area for other parts of the country, and we’re struggling to replace them.

We’re lagging in a key metric that often reflects the vitality and desirability of a metro area: population growth.

For comparison, consider our neighbor to the northwest. To some on the coasts, Minneapolis and Milwaukee are virtually indistinguishable. Two “M” cities in fly-over country, easily and often confused.

To be sure, the Minneapolis and Milwaukee metro areas do have some similarities. Besides the obvious — climate — we are places with abundant natural resources, including vast amounts of freshwater. Our economies feature more Fortune 500 companies than most similar-size cities. Both metros have plenty of cultural assets.

There also are important differences. Metro Minneapolis, which includes St. Paul and Bloomington, is home to the state’s flagship university and capitol. Metro Milwaukee is not. But there’s another significant differentiation: population growth. According to new U.S. Census Bureau population estimates, the Minneapolis metropolitan area added 306,000 new residents between 2010 and 2019. The Milwaukee metro area added 19,000.

The population of metro Minneapolis grew 9.2%. Metro Milwaukee grew 1.2%.

Minneapolis isn’t the only Midwestern metropolitan area that’s been growing.  Since 2010, metro Kansas City’s population grew 7.4%. Metro Indianapolis grew a whopping 9.9%. 

The new census estimates show that after a booming start to the decade, many metro areas around the country have seen growth rates decline in the last several years. But metro Milwaukee never experienced the boom.

## Milwaukee is near the bottom in domestic migration

As part of its Milwaukee Area Project, Marquette Law School’s Lubar Center for Public Policy Research and Civic Education compiled and analyzed publicly available data from 2010 to 2019.  It offers more insight into the population changes occurring in the Milwaukee Metropolitan Statistical Area (MSA), which the Census Bureau defines as Milwaukee, Waukesha, Ozaukee, and Washington counties.

Population change is determined by three things — birth, death and migration.

Of 384 metropolitan areas in the U.S., we rank 39th in total population, with about 1,575,000 residents.

We’re 46th in the nation in natural increase, which is births minus deaths. So far this decade, metro Milwaukee has had 59,000 more births than deaths. It’s a relatively healthy number. For example, the Pittsburgh metro area had 36,000 more deaths than births.

We are ranked 49th in net international migration. From 2010 to 2019, we attracted about 25,000 more people from another country than immigrated away. Again, hardly robust growth, but not terrible.

But something else is happening in metro Milwaukee, something that has serious implications for the region’s long-term economic health and vitality.

We rank 370th out of 384 metro areas in net domestic migration — movement within the U.S. In other words, there are only 14 metro areas in America that lost more residents to domestic migration than we did. 

Factor in our middling ability to attract international migrants, and we fall to 378th in total net migration — 378th out of 384 metro areas in the nation.

When you add up everyone coming here and subtract everyone leaving the metro area, we’ve lost about 39,000 people this decade. The only places that lose more people to migration are New York, Chicago, Los Angeles, Detroit, St. Louis and Cleveland. The only reason our population grew is because of a relatively strong birth rate. 

Most of our population loss comes from young adults. About 6,500 18- and 19-year-olds move to metro Milwaukee each year. But more than 10,000 leave and they don’t return in great numbers. We continue to experience net population loss among people in their mid-20s all the way through their early 30s.

Put another way, lots of kids are born here. Where we struggle is keeping them once they grow up, and in attracting new residents to replace them.

Metro Milwaukee’s current slow or no growth mode can be found in Milwaukee and its suburbs. In some respects, the population fortunes of communities in the region have converged. Places that were shrinking have stabilized or are treading water, while most places that were growing have seen their growth rates greatly diminish.

## Big population jumps in Milwaukee's suburbs have leveled off

The 1990s were a rags or riches decade for the area. Milwaukee and its inner-ring suburbs struggled. The city lost 5% of its population. Wauwatosa lost 4%, West Allis 3%.

At the other end of the spectrum, Mequon grew by 15%, Oak Creek an astonishing 46%.

Today, those kind of population swings in the metro area have generally evened out.

For example, Oak Creek’s population growth has steadily slowed. After adding 9,000 residents in the 1990s, it added 6,000 in the 2000s and 2,000 from 2010 to 2018. In a telling reflection of the metro area’s sluggish population growth, Oak Creek — now a city of 36,000 — still has the second-fastest rate of population growth among metro-area cities with at least 20,000 residents.

Some municipalities do better than others in attracting new residents. The city of Milwaukee is home to 38% of the metro area’s residents, but it attracts more than 42% of international immigrants and about 45% of those moving here from another state.

The city underperforms with people moving to the metro area from elsewhere in Wisconsin.  Those people are more likely to move to one of the suburbs.

Metro Milwaukee remains segregated by race. The population outside the city of Milwaukee is 85% white, though there is evidence that is slowly changing. The 2010s are the first decade in which the white population outside the city of Milwaukee has shrunk. From 2010-2018, it declined by 13,000, from 852,000 to 839,000.

During that same time, the number of black, Asian and Latino residents outside Milwaukee grew from about 90,000 to 120,000. Adding other racial identifiers to that total, there are about 145,000 people of color now living beyond the city limits.

The growth of the minority population outside the city has the potential to continue. Just one-third of white residents there are under 30, compared to 40% of Asians, 45% of blacks, and half of Latinos.

The question is whether this younger, more diverse population will remain in metro Milwaukee. When we launched the Milwaukee Area Project in 2017, we conducted a poll of the region’s residents.  We asked them to think about their community and their futures. Were they happy where they lived? Over the next five years, did they see themselves staying or moving?

Forty-seven percent of young white people said they were happy and planned on staying in their community. Only 6% of young whites said they were unhappy and planning to move. That was in stark contrast to young people of color. Just 22% said they were happy and planned on staying in their community. Another 27% said they were unhappy and planned to move.

Changing that reality will be one of the keys to metro Milwaukee’s population growth in the future.  The future success of the area in a post-COVID world depends on not just attracting new residents, but on giving the ones we already have good reasons to stay. 
