---
title: "Nature's Metropolis: Chicago and the Great West"
---

A stylized model of human organization might go like this: subsistence farmers meet in some central place to barter what little surplus they have with their neighbors. From that surplus, a village forms, supporting a few specialized jobs like blacksmith and doctor. The same process repeats at larger scales, creating gradually larger towns and culminating in the world’s great cities. William Cronin’s *Nature’s Metropolis: Chicago and the Great West* argues that this model gets the development of both Chicago and its vast hinterlands entirely wrong and arguably backwards. He uses four examples—grain, lumber, meat, and credit—to show how Chicago, rather than being the end point of some evolutionary social process, itself fundamentally shaped the development of its massive hinterlands.

In some ways, the history of what became the modern Midwest began with Chicago. Chicago’s adoption of not just the railroad, but equally importantly the grain elevator, transformed wheat from a bespoke product sold in bags and traceable from farmer to end-user into a “liquid” commodity, now abstracted into grades and sold in futures markets. Ever wonder why all towns on the Great Plains are built from wood? Those trains that brought the “liquid grain” east to Chicago had to go back west whether empty or full. Chicago provided the market for the great Northwoods to be clear cut, turned into dimensional lumber, and distributed across the interior of the continent at economically viable rates. 

Originally, that grain was wheat, but today, you will find scarcely a wheat field in Illinois and Iowa. Chicago is also to thank for that. Another way of taking grain to market is in the form of livestock. The creation of Chicago’s massive stockyards and slaughterhouses created a system by which cattle would be raised on the less agriculturally viable parts of the Great Plains, then shipped to feedlots in Illinois where farmers let them wander with hogs, both fattening on great quantities of locally-grown corn before their final voyage to the meatpackers in Chicago.

*Nature’s Metropolis* shines most in carefully articulating the logic shaping each market participant’s options. It’s common to look back at the Gilded Age as a time of robber barons, the exploiters and the exploited. In Cronin’s telling, Chicago and its hinterlands were both certainly exploiting the earth’s resources; in some sense, the old growth white pine and the prairie topsoil were lying there for the taking. Take them, they did. But at the human level, Cronin documents how the logic of capital worked to align the incentives of economic actors at all levels, even when this was not necessarily apparent to those involved.

Take meat. For consumers, the prices from the Chicago packers couldn’t be beat. Why? In large part because the immense economies of scale could extract more value from a single carcass than any local butcher. “The enormous volume of animals meant that even body parts that had formerly been wasted now became commercial products.” “In the new chemical research laboratories that the packers installed during the 1880s and 1890s, older by-products like lard and tallow were joined by more exotic items like oleomargarine, bouillon, brushes, combs, gut strings, stearin, pepsin, and even canned pork and beans.” This raised the price the largest packers could pay farmers and lowered the price those packers charged consumers. In fact, the large meatpacker Armour estimated that they sold the actual dressed beef at a loss; the profits came entirely from by-products.

Or take grain. Before the railroad, grain was shipped by farmers in sacks all the way to an end-buyer who negotiated a price based on that grain’s quality. The railroad, coupled with the grain elevator, changed this entirely. By 1860, railcars of loose grain were being emptied, sorted, and shipped in minutes without the use of human hands. Instead of prices determined uniquely for each lot of grain, grain was now assigned a grade and then commingled with other farmers’ grain of the same grade. Now, grain was a commodity. Disputes over the sale of grain futures, the assignment of grades, and the profits of elevators (the market’s true chokepoint) all followed for decades.

Whenever this centralization of the market occurred—whether in meatpacking, grain, or transportation—it was met by vehement opposition from small-scale producers who feared the pricing power of the new commercial giants and doubted the financial instruments they used. Out of this unrest grew the Grange and Populist movements. They “embraced the physiocratic doctrine that attributed all economic value to the tillers of the soil, the rest of society being entirely sustained by the farmers’ labors.” In this view, profits from trade were basically illegitimate and city “merchants were little better than thieves.” In response, the Grangers established their own buying and selling cooperatives, but “the rewards of cooperation proved much more elusive than farmers had expected.” Those cooperatives which “succeeded,” in the sense of remaining in business, achieved prices little different from the rest of the market.

Cronin diagnoses the failure of the agrarian populist movement as resulting from a failure to appreciate the economic forces at work. “[T]hey rarely recognized why manufacturers, wholesalers, and retailers relied on each other to do business. In effect, Grangers ignored—or didn’t believe in—the central place hierarchy and the distribution networks that went with it.” There are many lessons one could draw from Nature’s Metropolis, but this might be the most important: if you’re going to challenge a system, you have to understand the benefits its participants are receiving.
