---
title: "Growing 'land grab' by out-of-state investment landlords raises questions for Milwaukee homeowners and neighborhoods"
date: "April 15, 2021"
author: "Mike Gousha and John Johnson"
---

*This article originally appeared in the Milwaukee Journal Sentinel.*

Six years ago, Phoebe Alexander returned from an out-of-town family reunion to find a letter waiting for her at her northwest side apartment. It was from the city of Milwaukee. The owner of the duplex where she lived had failed to pay taxes. The city was taking ownership of the property near 90th Street and Silver Spring Drive.

The news was jarring. Alexander, her husband, and son had rented the lower level of the duplex for 11 years. But city housing officials didn’t want the Alexanders to leave. They wanted them to buy the duplex.

After thinking it over, the couple said “Yes.” Today, that decision to own instead of rent is paying off.

“I’m saving a couple hundred dollars every month,” Phoebe told us. “It’s cheaper in the end. There are just so many great benefits to being a homeowner.”

This is a story of what’s possible in Milwaukee: the prospect of owning your own home while saving money at the same time. But it’s also a story about a new kind of home buyer in Milwaukee — one who has little in common with families like the Alexanders and is increasingly in competition with them.

The full consequences of the pandemic on Milwaukee’s housing market have yet to be felt. A predicted surge in evictions is almost certain to be one of them. But another trend worth watching is what some have characterized as a legal “land grab” —  the acquisition of thousands of affordable city homes and duplexes by real estate investors who do not live in Wisconsin.

Previous research by Marquette Law School’s Lubar Center for Public Policy Research and Civic Education documented the plummeting number of owner-occupied residential properties in Milwaukee since the Great Recession. From 2005 to 2020, the owner-occupied percentage fell from 80% to 69% . Parts of the north and west sides saw declines double that.

Equally noteworthy is who is buying these residential properties. A new breed of distant, investment landlord has emerged. Since 2005, the number of residential properties owned by out-of-state landlords has quadrupled, from 1,300 to 6,000. Most of the properties are single-family homes or duplexes.

Initially, these out-of-state buyers mainly purchased properties that were recently owner-occupied. But when the number of foreclosures finally declined, the out-of-state landlords pivoted and began buying more properties from local landlords, often in bulk deals. Some are conventionally bank financed. Others are paid for strictly with cash. Most of the properties are valued at less than $100,000, often considerably less.

These are not the “flips” made famous by HGTV, where tens of thousands of dollars in improvements leads to profitable re-sales. A check of work-permit and property records for the last four years shows that out-of-state landlords applied for considerably fewer work permits than owner occupiers and even local landlords.

Instead, these properties are used to produce a steady stream of income for distant investors, with landlords often charging rents hundreds of dollars higher than what it would cost for someone — with just a small down payment — to own the home. The result is that that for some who can least afford it, Milwaukee is a more expensive place to live.

As part of the Milwaukee Area Project at Marquette Law School’s Lubar Center, we compiled and analyzed public records and data with the hope of answering several key questions: Why are these out-of-state investors doing business in Milwaukee? Have they continued to purchase homes during the pandemic? And how do the costs of renting vs. owning compare?

First, the backdrop. The Great Recession produced a nationwide housing reset. In the years following the housing crisis, Wall Street backed investment groups purchased large numbers of foreclosed properties in cities such as Los Angeles, Phoenix, and Las Vegas.

During a program at the Law School’s Lubar Center last fall, we talked with the author of "Homewreckers," journalist Aaron Glantz, who detailed the business model for these new housing investment LLCs. Glantz said they typically purchased newer homes in suburban areas with warm climates and significant job growth. And then they rented them, sharply raising monthly rents.

Milwaukee offers a different spin on the housing-as-investment model. Investors buy older, inexpensive properties, hold them, and earn steady income from renting them.

“You not only need to be worried about a land grab with homeowners losing their homes,” Glantz told us. “But you also need to be worried about mom-and-pop landlords, people who live in the community and have a stake in the community, losing their rental property and having it sucked up by people who live far away.”

## The impact of the pandemic

The increasing number of out-of-state landlords in Milwaukee reflects a nationwide trend. Single-family home rentals are a rapidly growing business model. In Milwaukee, their number has more than doubled since 2005. Currently 18,800 single-family homes are being rented inside the city limits. About half are valued at $75,000 or less. About 5,000 homes are valued at $50,000 or less.

For now, ownership of Milwaukee’s rented single-family homes and duplexes remains diffuse, spread among many different owners. But there are signs of consolidation. We estimate that a decade ago, the top 10 landlords owned a total of fewer than 900 houses. Now they own more than 1,800. Part of that consolidation is being fueled by the growing presence of out-of-state landlords. Ten years ago, none of the 20 largest landlords in the city was from outside Wisconsin. Today, six are from out-of-state.

Our analysis shows that one of every seven landlord-owned homes in Milwaukee is now owned by people living out of state, and that trend could accelerate further. Some smaller, local landlords have lost significant rental income during the pandemic and are now looking to sell their properties. Out-of-state investment funds often pay with cash.

In collaboration with Milwaukee Journal Sentinel investigative reporter Cary Spivak, we identified the nine largest out-of-state owners of houses and duplexes in Milwaukee. Again, these are landlords whose businesses are headquartered outside of Wisconsin. They include individuals from California, Texas, Ohio, and Illinois. Details about their operations can sometimes be difficult to discern, with investors often using multiple LLCs with different names for their acquisitions.

There are exceptions. Three of the most prolific buyers of residential properties in Milwaukee in recent years have polished websites, touting their business models and success.

At the end of 2020, the nine out-of-state landlords we identified owned 989 properties in Milwaukee, holding more than 1,500 units. They owned 670 single-family homes, 268 duplexes, 34 apartment buildings, and 17 other residential buildings, valued in total at $79 million. We estimate that in a normal year, city residents will pay these out-of-state landlords more than $16 million in rent. All the landlords entered the Milwaukee market after the worst of the housing crisis. 

For this story, we took a closer look at five of the landlords.

Bulldog Ridge is led by a Chicago-area real estate investor and has a suburban Chicago mailing address. Along with a handful of associated LLCs, it owned 178 Milwaukee properties at the end of 2020, including 108 single-family homes, 54 duplexes, and 11 apartment buildings. Most of these properties are in the near south side, north side, and Sherman Park areas. The median price of the homes and duplexes owned by Bulldog Ridge is $57,400. Its lowest price home is valued at $21,600. Its most expensive is $187,800.

Milwaukee Capital, along with sister company SCV Ventures, is led by a real estate investor based in Houston and Florida. Milwaukee Capital’s properties are found in some of the city’s most impoverished neighborhoods, primarily on the near north and near west sides. It ended 2020 with 115 properties in Milwaukee, including 66 single-family homes and 45 duplexes. The median value of the properties it owns is $42,050. That includes a home assessed at $2,800. Many of the properties had been owned by a real estate investment business once associated with former professional basketball player and Milwaukee native Devin Harris.

SFR3, started by two technology company executives in the San Francisco area, began buying homes in Milwaukee in 2017. Along with an associated LLC, SFR3 owned 95 properties in the city entering 2021. Eighty-seven of those are single-family homes; eight are duplexes. SFR3 operates largely on the far north and northwest sides. Its median price house is valued at $89,700, but it owns homes ranging in value from $20,100 to $167,800. Its website touts “affordable homes for America’s workers,” and says its mission is “to renovate old houses in disrepair” and make them “like new.”

VineBrook Homes is based in Dayton, Ohio, and was started by a successful venture capitalist. The company operates in other Midwestern cities, including Cincinnati, St. Louis, and Memphis. It began purchasing homes in Milwaukee in 2019, mostly on the west and northwest sides, using an LLC named “VB One.” It entered 2021 owning 250 properties: 235 single-family homes and 15 duplexes. The median value of its homes is $84,400, with its least valued property assessed at $33,400 and its most expensive valued at $201,800.

As the Journal Sentinel’s Spivak has reported, the economic fallout from the virus has caused both tenants and landlords to struggle. Property records indicate that most out-of-state investors we identified have paused their purchases of Milwaukee properties during the pandemic and subsequent eviction moratoriums. But several have continued to aggressively buy.

From mid-March to December 2020, VB One purchased 147 homes in Milwaukee with cash. It bought 29 in just the month of December. Virtually all the properties were on the north and northwest sides of the city. In one two-day period in early May 2020, VB One purchased seven single-family homes.

From mid-August to December, SFR3 purchased 39 properties in Milwaukee. Most were single-family homes. Most were paid for in cash. On a website, a representative of SFR3 identifies himself as a “Cash Buyer for Milwaukee,” and writes, “I’ve been tasked with buying 20 house(s) per month. Please reach out if you have any properties that might work.”

A fifth landlord, based in southern California, was also busy buying Milwaukee duplexes last year, most on the near north side. The investment firm, which purchased 95 homes last year, has acquired properties here using names including “Copper Kettle” and, more recently, “Residential Properties Resources Fund ll LLC (RPRF).”

The LLCs are connected to a real estate investment fund called Highgrove Holdings Management LLC, of Torrance, Calif., which maintains a website with an entire page describing investment opportunities in Milwaukee. The website states that the price of a property purchased for investment purposes, including rehabilitation costs, averages $35,000. Our data analysis shows the firm’s average property is worth $32,600.

In addition to promising investors “12%-18% returns annually,” Highgrove’s website says the firm “focuses on cleaning up communities where purchases are made. Focus will always remain on safety, clean environment and good service for our tenants.”

The website also describes Highgrove’s aspirations, saying, “Highgrove has been working closely with real estate professionals in Milwaukee to seek out and acquire properties in the area at discounted prices up to and in some cases exceeding 50% off of fair market value. The goal of HHM is to amass 1,100 properties in Milwaukee.”

## Why Milwaukee?

What makes investing in Milwaukee, an older Midwestern city with stagnant population growth, lucrative?

First, thousands of homes in the city are valued at less than $100,000, in some cases much less. They are easily affordable to investors looking to buy. Second, in a normal year, they generally offer an excellent return on their investment.

How do we know that? While we have not seen balance sheets for out-of-state landlords, we created a model using publicly available records and data that help explain what's happening:

* We estimated rents by collecting market-rate estimates of each property’s value. Our analysis found that these estimates typically vary from actual rental listings by 10 percent or less.

* We estimated average management expenses by comparing the rates of eight local management companies to estimate a typical total management fee of 10.9% of rent. This includes tenant placement fees.

* Based on a formula used by the real estate data firm CoreLogic, we estimate maintenance fees as 17.5% of rent and insurance as 0.35% of the assessed property value.

* We examined city records, to include taxes and assessments, but did not account for extra expenses such as legal fees and loan payments, which vary from landlord to landlord.

Using this model, we calculated potential financial returns for all nine of the larger out-of-state investors. We will focus on two of them.

Milwaukee Capital, the Houston-based LLC, owns properties in some of the poorest sections of Milwaukee. From 2018 to 2020, it spent $4.3 million acquiring 115 properties in the city. Those properties are now assessed at $4.8 million. Most were acquired in bulk, bank-financed purchases. The company’s history of accumulating building code violations at a pace five times the citywide average for landlords suggests it has invested little in rehabbing its properties.

If Milwaukee Capital charges market value rates for its units and matches the citywide occupancy average, that would bring in $1.7 million each year. Subtract estimated management expenses of $182,000, property taxes of $124,000, maintenance costs of $291,000, and insurance premiums of $17,000 and you would have net annual revenue of approximately $1.1 million. That is, in just one year, 25% of the amount spent to purchase these properties. Again, this represents a more typical, non-pandemic year.

The leading out-of-state buyer of Milwaukee residential properties in recent years has been VB One, which lists a Dayton address. In 2020, it purchased 173 houses. No one else bought more than 95.

In less than two years, VB One has spent $21 million acquiring 250 properties currently assessed at a total of $21 million. Charging market-rate rents at the city’s occupancy rate would bring in annual gross revenues of $3.4 million. We estimate property management expenses of $369,000, property taxes of $554,000, maintenance costs of $590,000, and insurance premiums of $74,000, leaving net revenue of $1.8 million, or 8.7% of the entire amount spent to purchase these properties. All were paid for with cash.

As of June 2020, VineBrook reported an average rehab cost of $16,000 per property across its entire portfolio. Assuming it invested the same amount in Milwaukee would lower its profit rate here to 7.2% of its total investment. VineBrook Homes is a vertically integrated real estate firm that provides construction and property management services in-house, likely for a lower cost than that of local contractors.

## The advantages of owning vs. renting

What also makes Milwaukee lucrative is that rental rates for cheaper properties remain relatively high. We compared annual rent to total property value for residential properties owned by out-of-state landlords. For properties under $100,000, we found only a small relationship between home values and rents. Typical rent for a $40,000 single-family home is only about 10% cheaper than rent for an $80,000 house.

According to Mike Gosman, the president and CEO of the nonprofit Acts Housing in Milwaukee, owning instead of renting is a better deal for many low- to moderate-income working families.

“The math is very compelling. A lot of people are just unaware of the fact that they might be able to save $300 or $400 a month through homeownership,” Gosman said.

In the last year, Acts has helped more than 160 low- to moderate-income families purchase homes. The nonprofit provides services needed to transition from renter to homeowner, including home-buyer counseling, its own real estate agents, and guidance for repair projects. In addition, Acts is often the lender, with an active portfolio of 100 loans made to families fixing up and purchasing distressed homes.

“Typically, families who purchase one of the distressed homes have total costs of $650 per month,” Gosman said. “It is very common for us to have families spending $900, $1,000, $1,100 a month to rent. And frankly, they’re renting places that are not decent.”

Gosman’s estimate of savings is supported by data analysis done for this story.

We estimated ownership costs by assuming a 5% down payment, a mortgage with an annual percentage rate of 4%, and a 30-year loan. We included other ownership costs of $1,000 a year: homeowner’s insurance, 1% private mortgage insurance, property taxes at 2.6%, city utilities at $200 per quarter, and monthly maintenance expenses calculated as 17.5% of the housing unit’s total rent.

Our analysis found a dramatic difference between ownership and rental costs. We estimate that the average renter of a $75,000 single-family home pays about $227 more a month than it would cost to own the property. And the average renter of a $50,000 home pays $360 more per month than it would cost an owner with normal expenses.

Gosman said there is huge demand from working families to fix up and purchase homes, but he acknowledged there are challenges that must be overcome.

Phoebe Alexander, whom we met earlier, knows those challenges first-hand.

“I always wanted to buy a house,” she said. “But we knew there were some things in our past that we needed to clean up financially. We kept asking ourselves, how are we going to do this?”

The Alexanders had gotten into financial trouble when Phoebe had not one, but two jobs eliminated through corporate downsizing. While she said the purchase price for their northwest side duplex was “very reasonable,” the property required more than $30,000 in repairs. The couple also needed a down payment.

It took nearly five years of working with Acts Housing for the Alexanders to repair their credit history, save money, and become eligible for financing. Finally, in July 2019, the Alexanders’ perseverance paid off. They closed on their property. Now in their 50s, with steady jobs, the family is living their version of the American Dream.

Gosman told us that the Alexanders’ story illustrates the obstacles that often stand in the way of ownership. Families may have debt and credit issues or not enough money for a down payment. That can discourage institutions from lending. Other families are simply living on the margins. Previous Lubar Center reporting found median income for Black households in Milwaukee is just $30,000 a year.

Still, Gosman said many issues can be resolved through financial counseling. Of his organization’s 100 outstanding loans, only 1% are delinquent, even during the pandemic.

But the growing presence of out-of-state investors has created another challenge.

“This is the most competitive market for low- and moderately-priced homes that our organization has ever seen,” he said. “It means that every single additional entrant in the market is competition for our families, who are not in a position to make cash offers.”

Our analysis did not look at the impact of these purchases on Milwaukee neighborhood values or at how properties are maintained. On their websites, the investment groups say they are meeting a need for single-family rental housing.

But at last fall’s housing program at the Lubar Center, Milwaukee Common Council President Cavalier Johnson expressed concern that out-of-state ownership can make it harder to address issues with a troubled property. “That ultimately affects the stability and cohesiveness of neighborhoods, and that’s trouble,” Johnson said.

City Development Commissioner Lafayette Crump told us that Milwaukee is not alone in seeing a growing number of out-of-state landlords. With interest rates at historically low levels, he said individuals are seeking alternatives for investment.

Crump said that out-of-state landlords and investment funds still own only about 5% of the city’s single-family homes and duplexes. He said the increased out-of-state investment is “worth keeping an eye on but not necessarily a cause for alarm at the moment.

“We do believe local ownership is important and that people who live in and have a vested interest in the city are more likely to do a good job of being responsible owners,” Crump said.

“We do not want to cede portions of the city to external investors or control.”

The city is taking steps to increase and maintain owner-occupancy, Crump noted. That includes working with local partners, including emerging developers and nonprofits, to provide city-owned properties, financial resources, and support for the development of one- and two-family properties. Some will eventually be turned over to homeownership.

Crump said that when the city sells properties, preference is given to owner-occupiers. It is about to launch a pilot program that does the same for existing city homeowners interested in buying properties near their home.

Crump said Mayor Tom Barrett’s 2021 budget also includes a new down payment assistance program. “Our goals in this area are not only to increase owner occupancy, but to preserve it,” Crump added.

Gosman’s organization hopes to help 220 more families purchase homes this year and plans to lend an additional $2 million, almost doubling its portfolio. Still, creating awareness of what is possible remains a challenge.

“The biggest obstacle is that people just don’t believe that homeownership can be for people like them,” Gosman explained.

Phoebe Alexander agreed.

“I think there are more people out there that would love to own homes, but they need help in getting started,” she said.

As she described her home’s most recent improvements, Alexander’s excitement spoke to one of the key differences between local and long-distance home ownership. For her, it’s more than just a financial investment. It’s personal.

“I told my husband I don’t want anything for Christmas because I’ve got my stainless-steel sink,” she said. “You can make a house your own. That’s what I love about it. When I turn the key, I’m turning the key to my home.”

## Epilogue

VineBrook Homes continued to expand rapidly in the early months of 2021. In early February, it announced the acquisition of 1,866 more single-family homes across “seven new markets in Alabama, Georgia, North Carolina, and South Carolina.” From January through mid-March, it purchased about 90 more houses in Milwaukee. SFR3 and Highgrove Holdings have also continued their Milwaukee acquisitions, though at a slower pace than VineBrook.