---
title: "Census shows the Milwaukee area is more diverse, but overall growth remains sluggish"
date: "September 23, 2021"
author: "Mike Gousha and John Johnson"
---

*This article [originally appeared](https://www.jsonline.com/story/news/solutions/2021/09/23/census-milwaukee-area-more-diverse-but-overall-growth-sluggish/5786829001/) in the Milwaukee Journal Sentinel.*

It was an indelible image from a metropolitan area long known for its racial divide.  As the Milwaukee Bucks pursued an NBA championship last July, tens of thousands of cheering fans stood shoulder to shoulder in the Deer District outside Fiserv Forum to watch the games on massive TV screens. The size of the watch parties was impressive. But what made the nightly celebrations memorable was the remarkable diversity, a sharp contrast to so many social gatherings in Milwaukee. Young and united by their love of the Bucks, the colorful crowds gave us a glimpse of the future, of what metro Milwaukee could be.

Today’s reality is less idyllic. Most people of color live in the city. Most suburbs are largely white. In fact, new analysis of the 2020 U.S. Census Bureau count by the Lubar Center for Public Policy and Civic Education at Marquette University Law School reveals that metro Milwaukee still leads the nation in Black-white residential segregation, just ahead of New York, Chicago, Cleveland, Detroit, St. Louis, and Buffalo.  

But beyond that headline, a more nuanced story is playing out in metropolitan Milwaukee. We’re changing, becoming more diverse and less segregated, even as we experience stagnating growth.

* The new census count shows that the number of Hispanic, Asian, and Black suburbanites grew by tens of thousands, thanks to both in-migration and new births.  Cities such as West Allis, Brookfield, Greenfield, and Brown Deer led the way in this long demographic transition.

* For the first time in the metro area’s history, non-Hispanic white people were no longer the majority in two Milwaukee County suburbs — Brown Deer and West Milwaukee.

* In the city of Milwaukee, Black, Hispanic, and Asian residents moved into areas that have been historically white. This resulted in sharp population losses in north and near south side aldermanic districts.

* The city of Milwaukee’s population loss was almost entirely the result of fewer children. The number of housing units went up, but household size went down.

* The white population in the metro area declined, down tens of thousands of residents from a decade ago.

* Population growth in the metro area was far more sluggish than most of its Midwestern peers.

These are some of the key findings from analysis conducted as part of the Lubar Center’s Milwaukee Area Project. The new census count shows a metro area stuck in a slow-growth mode. Population in the four counties — Milwaukee, Waukesha, Ozaukee and Washington — stood at 1,574,731 in the new census count. That’s an increase of 18,823 people in the last decade. The 1.2% growth rate is the metro’s second lowest ever, surpassing only the 1970s, when the population actually declined.

The census data also reveals a marked change in how Americans identify themselves. The number of people identifying as two or more races grew by 127% nationwide and 115% in the Milwaukee metro. The share of Milwaukee area residents simply marking “Some Other Race” grew by 309%.

Traditionally, researchers have focused on “race alone” statistics, because bi- and multi-racial individuals were a small group. Given the large increase in people choosing multiple races, considering both groups — race alone and race in combination — is necessary to get an accurate sense of the population.

The Census Bureau asks about Hispanic or Latino identity separately from race, so these numbers include respondents of any race. The numbers below for white, Black, Asian, and Native American people are for people who didn’t identify as Hispanic or Latino.

## Hispanic or Latino population growth was strong

However measured, some things are very clear. Across the entire metro, the Hispanic or Latino population increased by 35,300, or 24%. Without strong Hispanic population growth, metro Milwaukee would have seen its population decline.

The Asian population grew as well. The population of those identifying as “Asian alone” increased by 20,200, or 44%, while “Asian in combination” grew by 5,100.

The white population in metro Milwaukee declined. The population of those identifying as “white alone” fell 63,400 or 6%.  That was partially offset by a 28,300 increase in those identifying as “white in combination with something else,” but however you measure it, the white population in metro Milwaukee is smaller today than it was a decade ago.

Changes to Black and Native American population totals were less clear. The “Black alone” population declined by 5,600, or 2%. But “Black in combination” increased by 7,800.

The number of people who identified as “American Indian and Alaska Native” declined by 1,500, or 22%.  But the number choosing this in combination with another race —usually white — grew by 8,600.

In addition to the way people identified themselves, some of the most striking findings were the dramatic population changes within the city of Milwaukee. The Census Bureau said the city lost 17,609 residents in the last decade. Its population now stands at 577,222, a 3% decline in the last decade and the lowest population since 1930. Some city officials have suggested there was an undercount, a claim we’ll address later.

According to the census data, all but four of the city’s 15 aldermanic districts lost population, with the steepest declines on the north and near south sides.

On the north side, the 15th district lost 4,800 residents. The adjacent 6th district lost 4,200. The population of the 7th district fell 3,300. The population loss also extended further northwest, to the 2nd aldermanic district, which saw a decline of 2,900 residents.

On the near south side, the 8th district lost 2,500 residents, the 12th 2,000.

Some of that population loss was offset by growth in other parts of the city, including downtown, the Third Ward, the Lower East Side, and Walker’s Point neighborhoods.

The 3rd aldermanic district covering the east side grew by 2,400 people. The 4th district covering downtown and the near west side gained 1,700 residents.

There was also growth on the far south and southwest sides. The 13th Aldermanic district added 1,700 new residents. The 11th added 1,600.

At first glance, that may be surprising. After all, these far south and southwest neighborhoods have historically been popular with public employees, and the end of the residency requirement affected these areas the most.

Looking at maps of population change by race suggests a possible explanation for the population increases. There has been a notable increase in the Hispanic population in the far south and southwest sides, plus an increase in the Black population in the Enderis Park area and far northwest side. The exit of public employees from these historically desirable neighborhoods may have created an opportunity for Black and Hispanic residents of the city’s more central neighborhoods to move outwards.

## Milwaukee becomes somewhat less segregated

The population shifts in the last decade have resulted in the city becoming less segregated. The Hispanic population declined on the near south side and increased in most other parts of the city. The Black population declined on the near north side but increased in historically white areas. The white population declined everywhere except along the lake and parts of the near west and near north sides. The Asian population increased everywhere, particularly on the far south side.

Overall, the share of Milwaukee’s population identifying as Black alone fell by 15,100 in the last decade and stood at 38%. Another 2% identified as Black in combination with another race — usually white.

White alone fell by 33,800 to 32%. Five percent more identified as white plus another race.

Hispanic or Latino increased by 13,300 to 20%.

Those identifying as Asian alone increased by 9,400 to 5% of the city. Another 1% identified as Asian in combination with at least one other race.

The population identifying as Native American or Alaska Native fell by 1,000 to less than 1%, but the population choosing this identity in combination with something else grew by 800.

Like the city, there is increasing diversity in Milwaukee’s suburbs. The total number of suburban residents identifying as white (either alone or in combination) declined by 8,300, or 1%, over the last decade — the first such decline in any census. The biggest decreases were in West Allis, which has 6,500 fewer white residents than a decade ago. Greenfield lost 2,600 white residents, the city of Waukesha, 1,900.

The white population grew the most in Oconomowoc and the city of Pewaukee, which added 2,100 and 2,000 respectively.

The Black suburban population grew roughly 50%, adding 14,100 new residents. The biggest increases were in West Allis, which added 2,000 Black residents. Brown Deer added 1,400 and Wauwatosa 1,200.

The Asian population in the suburbs also grew by 50%, adding 14,600 new residents. The biggest increase was in Brookfield, which added 2,500. Menomonee Falls had 1,300 new Asian residents.  Oak Creek had 1,100.

The Hispanic population in the suburbs grew by 18,200, an increase of 38%.  The Latino population grew by 3,800 in West Allis, by 1,800 in Greenfield, and by 1,000 in Waukesha.

The census data also shows that for the first time, two suburbs, West Milwaukee and Brown Deer, were majority minority. Only 46% of West Milwaukee residents were non-Hispanic white in 2020, down from 61% a decade ago.  In the latest census, 48% of Brown Deer residents identified as white. Ten years ago, 62% were white.

Still, the two suburbs remain outliers in metro Milwaukee. The third most diverse suburb was West Allis, where non-Hispanic white residents made up 73% of the population. Greenfield was 75% white, Cudahy 78%, Waukesha and Oak Creek, 79%. All other suburbs were at least 80% white.

The suburbs surrounding Milwaukee continue to fuel what population growth there is in the metro area. Brookfield added 3,500 new residents in the last decade, Menomonee Falls grew by 2,900. Oak Creek and Mequon both added more than 2,000 residents.

There was also growth in the far western suburbs. The city of Pewaukee added 2,700 residents, a 21% increase in population. Oconomowoc grew by 2,400, a 15% increase.

Yet there are signs that population growth is slowing outside the city. One suburb, South Milwaukee, lost nearly 400 people. Waukesha County added 17,100 people in the last decade, an increase of 4.4%. But that is the lowest growth rate for the county since the 1870s.

Washington County grew by 4,900 new residents, an increase of 3.7%.  That’s down from 12.3% in the 2000s, and 23.3% in the 1990s. This is the first decade since the 1930s in which Washington County didn’t experience double-digit growth.

As part of our analysis, we compared metro Milwaukee’s population growth in the last decade to that of other Midwestern cities. The only significant metro that grew more slowly was Cleveland’s, which had a population increase of 11,000, a 0.5% growth rate. Again, metro Milwaukee added approximately 18,800 people, for a growth rate of 1.2%

During the same period, metropolitan Madison added 75,400 people and grew at a 12.4% rate. The Indianapolis metro area added 223,200 residents, an 11.8% increase. The population of the Minneapolis-St. Paul metro was up 356,600 over a decade ago, an increase of 10.7%. Kansas City’s metro area grew by 182,700, a 9.1% increase. Metropolitan Cincinnati’s population increased 119,200, or a rate of 5.6% growth.

The metropolitan Chicago area grew at a pace more like ours, 1.7%. St. Louis had the same growth rate as metro Milwaukee, 1.2%

If you compare only cities, and not metro areas, Milwaukee’s 3.0% decline was better than St. Louis, which lost 5.5% of its population, and Cleveland, which lost 6.1% of its residents.

On the other side of the ledger, Kansas City, Minneapolis, and Madison all grew by double digits.

In the new census count, the Milwaukee area ranked as the 41st largest metro in the country. It was 40th 10 years ago.  The area ranked 285th out of 392 metro areas in the rate of population growth in the last decade.

All measures of Milwaukee’s population agree that there has been a decline since 2010. The size of that decline in the 2020 census came as a surprise because it was 12,600 people fewer than the most recent estimate from the Census Bureau’s Population Estimates Program (PEP), which is calculated using administrative data on births, deaths, and migration. 

Some observers have suggested the census undercounted Milwaukee, but another explanation is plausible. Compared with the 2020 census, PEP much more accurately estimated the county’s population as a whole but assigned too much of it to the city and too little to the suburbs. PEP used the 2010 average household size to divide the county’s population into municipalities. But in the latest census, Milwaukee City’s average household size declined, while the suburbs stayed about the same. Take a typical set of 20 homes in Milwaukee and about two fewer people live in them now, compared with 2010.

According to the census, the number of children in Milwaukee declined by 16,900 —consistent with shrinking household sizes. Total housing units actually increased over this period, but typical new construction was designed for singles and couples instead of families with kids. Even as the number of kids plummeted, the census counted only 700 fewer adults in Milwaukee.

Other data sources also show fewer children. For decades, the number of kids being born in Milwaukee has been smaller than the number of kids born 18 years previously. About 16,000 fewer babies were born during 2010-2019 than during 1992-2001—the cohort who became adults during the 2010s.

Population growth is not necessarily the only or even best way to measure the health and vitality of a major metropolitan area. Bigger is not always better, if it means a diminished quality of life for its citizens.  

But population growth does tell us something about whether a city or metro area is viewed as a desirable place to live, work, and raise a family.  The images from the Deer District in July spoke volumes about the possibilities of Milwaukee, about the destination we could be in the future. The new census count suggests we’re not there yet.
