---
title: "Homes in metro Milwaukee have long been considered affordable. Is that still true?"
date: "October 9, 2024"
author: "Mike Gousha and John Johnson"
---

*This article [originally appeared](https://www.jsonline.com/story/news/2024/10/09/can-a-typical-worker-still-buy-a-home-in-milwaukee-increasingly-no/75394180007/) in the Milwaukee Journal Sentinel.*

For a moment, imagine you’re a mail carrier. You’re early in your career and make just over $48,000 a year, or the median wage for all workers in the Milwaukee area. Could you buy a house in the city of Milwaukee on your salary alone?

The answer — which we’ll share later in this story — can help us better understand Milwaukee’s evolving housing picture.

Owning a home has long been a part of the American dream, and for those looking to buy, especially first-timers, the state’s largest city offered access. Milwaukee featured dozens of neighborhoods where middle and working-class residents could afford to buy a house, often on a single income. But the city’s housing market changed dramatically in recent years. For many prospective homebuyers, what was possible only five years ago is no longer realistic today.

In our latest Milwaukee Area Project examining life in the metro, we sought to answer the question: Is housing in the city (and its suburbs) still affordable? We focused on the period from 2019 to 2024 — from before the pandemic upended existing economic trends to where the housing market is today.

Some of what we discovered wasn’t surprising. Buying a house is more expensive today, relative to income, than at any point in the last two decades. This is true in Milwaukee and the nation. The increase in housing costs in the last five years outpaced wage gains. That resulted in a growing number of workers in the metro area being priced out of the market.

It's also true that the city of Milwaukee remains a relative “bargain” compared to other major cities — not just Los Angeles, San Francisco, and New York, but Minneapolis, Chicago and even Madison.

Buying a house in the city of Milwaukee is significantly more affordable than the national average. This has been the case for decades and it’s still true today. For most of the last 25 years, the metro’s median salary was enough on its own to purchase the typical house in the city. Buying a house was even easier for households with two wage earners.

Still, costs here have risen enough to challenge the value proposition of owning a home. Our research found that even among single-family homes in the city of Milwaukee, it is now generally cheaper to rent than to buy.

When we talk about what is affordable, we use the definition the U.S. Department of Housing and Urban Development uses. Standard financial advice is that a household should spend no more than 30% of its gross (pre-tax) income on housing expenses. Some are comfortable with spending more, but the 30% guideline is a good measure of affordability.

Escalating costs, even in comparatively affordable Milwaukee, are making homeownership more difficult. A typical less expensive (25th percentile) house in the city cost about $71,000 in 2019. Today it costs $126,000, a 77% increase. An average home cost $126,000 in 2019. Today, it goes for $206,000. And a more expensive (75th percentile) home in the city went for just shy of $200,000 in 2019. Today, that home sells for $294,000.

Further, while we hear a lot about homes selling for cash offers, that’s not the way most prospective homebuyers will buy a house. They’ll need a mortgage. So, the number that really matters is not the home’s sticker price, but the monthly payment they can afford. That payment includes principal, interest, taxes, and insurance.

Those monthly payments increased far faster than home values because of rapidly rising interest rates and increasing home insurance rates. To get a better sense of what’s happened, we assumed common characteristics for a first-time homebuyer, including 5% down and 1% private mortgage insurance. We found that the monthly cost to buy the average home in the city jumped from $1,023 in 2019 to $1,877 in 2024.

In 2019, the monthly payment needed to buy the average city of Milwaukee house worked out to 30% of the median full-time salary in the metro. That jumped to 45% in 2024 (based on preliminary salary estimates).

While two wage earners in a home can help with the affordability issue, it’s worth noting that [our previous research](https://www.jsonline.com/story/news/2024/06/27/milwaukee-families-have-radically-changed-in-50-years-over-50-years-present-challenges-opportunities/73171781007/) found that single-person households now make up more than one-third of the households in the city.

Even in 2019, the city of Milwaukee was the only municipality in the county where a single average wage earner could afford the average house by themselves. That affordability is due in part to a larger supply of smaller homes. It also reflects concerns about crime and struggling schools, which depress prices in some neighborhoods.

But in Milwaukee County, at least, a couple — each earning the average salary — could still afford the average home in most suburbs. That, too, is more challenging today.

The ranks of affordable suburbs shrank considerably in the last five years. By 2023, only seven of 19 Milwaukee County municipalities were affordable for a family with two median wage earners (a total of $97,000).

Here’s another way to look at this trend. We identified professions with incomes closest to the affordability threshold, where monthly house payments equal 30% of the average wage.

In 2019, a typical first-line factory supervisor making $63,000 could afford the average house in Greenfield. In 2023, it took a salary of $100,000 to afford that same house, typical of what electrical engineers earn.

In 2019, a typical tool and die maker with a median salary of $52,000 could afford the average house in West Allis. In 2023, it took a salary of $83,000 to afford that house, typical of what a registered nurse earned.

Other occupations saw homeownership slip out of reach entirely.

We also looked at the cost of houses in Waukesha, Ozaukee and Washington counties. Buying a home in the WOW counties is considerably more expensive than the national average. In Waukesha, the price of the average house grew from $324,000 in 2019 to $455,000 in 2024. In Ozaukee, it jumped from $335,000 to $452,000. In Washington, historically the most affordable of the three counties, the average home went for $277,000 to $392,000.

A key factor in why housing affordability remains elusive for so many is wage growth in the metro area. Wages rose in the last five years, but not nearly as quickly as home prices.

Data from the Bureau of Labor Statistics shows that in 2001 workers in metro Milwaukee earned a bit more than workers nationally. This was true across the board, for those making a little and those making a lot. For example, an average paid worker in metro Milwaukee made about $1,330 more a year than the national average.

But by 2023, higher earners in metro Milwaukee had fallen behind the national average. One noteworthy example: the highest paid workers in metro Milwaukee took home $610 more than the national average in 2001. In 2023, they made $16,330 less.

Workers in the bottom half of the income ladder overall still were above the national average, but their advantage had shrunk. And the lowest paid workers had fallen behind. In 2001, they made $1,170 more than the national average. In 2023, they made $720 less.

The sharp increase in housing prices and the jump in monthly costs for ownership could lead some to reconsider the benefits of owning a home. That's a significant change. As late as 2020, we found that owning a home usually resulted in lower monthly costs than renting a single family house, even when including maintenance costs.

Today, it’s a different story. That's because, even among single family homes, the monthly costs associated with ownership have increased so much faster than the cost of rent.

Researchers know considerably less about the rental market than home values. The results of every property sale are publicly available, but there is no central repository for information about rents. So, we turned to the private company Zillow, whose data and methodology offer the best insights into the local rental market.

From 2019 to 2024, the monthly costs needed to buy an average home in the city of Milwaukee grew by $854 or an increase of 83%. The average monthly rent grew by $316, or 31%. Put another way, the monthly payments associated with homeownership — nearly $1,900 — were $550 more than the typical rent.

That was true elsewhere in the metro. Typical rents in Milwaukee and Waukesha counties, for example, grew about 30%. For those workers most likely to be renting (those in the bottom half of the income ladder) wages grew faster than inflation in the early 2020s, closely tracking the growth in rents while trailing skyrocketing ownership costs.

Despite claims that rents here have risen unusually quickly, the data suggests otherwise. Among the nation’s 100 largest metro areas, rent increases in metro Milwaukee ranked higher than most in the last year. But from 2019 to 2024, our percentage growth in rents was slower than in all but 25 of the nation's 100 largest metros. Metro Milwaukee had the 21st cheapest rents in 2019, among the largest 100. In 2024, it was the 13th cheapest.

Still, that comes as little consolation to those on fixed incomes in the metro, a surprisingly large number. Our research found that more than a quarter of renter households in the metro Milwaukee area include no employed people. Most are likely retirees while others are students or live on public assistance. Affording rent has likely become much more difficult for them.

For some, the last five years have been an enormous source of frustration. Their hopes of buying a house became increasingly bleak. In the city of Milwaukee, prospective working-class homebuyers often found themselves shut out of the market as prices for inexpensive and average houses rose sharply, interest rates spiked, and out-of-state investors went on a buying spree. In 2019, nearly a quarter of the city’s houses cost $71,000 or less. Today, that market has largely disappeared.

To put it in more personal terms, let’s return to our example of the early career mail carrier. With careful budgeting, that postal worker could have afforded the average house in Milwaukee in 2019. Today, that is no longer the case.

What also makes the last five years frustrating for some is that they missed an opportunity to save money and build wealth. In 2019, the monthly cost needed to buy the average house was about $850 lower than in 2024. Property records show that more than 3,100 present-day homeowners bought their house in 2019. By staying current on their payments, we estimate that they have built, on average, $78,000 in equity.

In several years of writing about housing in the Milwaukee area, we have been struck by how quickly the market can change. With a new push for more housing and the prospect of lower interest rates, it may pivot yet again in the coming years. Owning a house may continue to be part of the American dream.

But for now, in metro Milwaukee, that dream is harder to realize.

Data Note: We used several data sources in this analysis. Home value data is from the smoothed, seasonally adjusted version of the Zillow Home Value Index. Rent data is from the smoothed, seasonally adjusted Zillow Observed Rent Index. Wage data is from Bureau of Labor Statistics Occupational Employment and Wage Statistics program. The BLS calculates annual full-time wages by multiplying hourly rates by 2,080. All annual estimates are as of May of each year. We estimate monthly PITI payments using mortgage rates provided by Freddie Mac, gross municipal tax rates from the Wisconsin Department of Revenue and the Wisconsin Policy Forum, and insurance premiums from Census Bureau.

For complete methodological details and additional analysis, see the Marquette Law School Faculty Blog post with the same date as this article.
