---
title: "Marriage and birth rates, household size, all drop sharply in Milwaukee over 50 years"
date: "June 27, 2024"
author: "Mike Gousha and John Johnson"
---

Cities are always evolving. Like the people who call them home, they experience highs and lows, moments of celebration and disappointment. Their economic fortunes rise and fall depending on factors both within and beyond their control. The constant is change. The challenge is to adapt. 

That is certainly true for Wisconsin’s population center — Milwaukee and Milwaukee County. In the last 50 years, the state’s largest city and county underwent enormous change. To begin with, they shed thousands of residents. An estimated 916,000 people lived in Milwaukee County in 2023, roughly 125,000 fewer than 50 years ago. The population decline was driven by the city, which lost more than a fifth of its residents during the same period. 

Some of the changes are easy to see. We are a far more diverse area today than we were a half century ago. The city’s once-modest skyline now features several prominent high-rises. But one of the most significant changes that occurred is less obvious to the eye. We are talking about the evolution of a key social institution: the family. 

The family in America changed significantly in the last half century. A 2023 Pew Research Center survey found that only about a quarter of Americans now see marriage and parenthood as key to a fulfilling life. People are marrying later, with fewer people marrying at all. Birth rates are falling.  

Each of those trends is playing out in Milwaukee, but on steroids.  

As part of the Milwaukee Area Project, our continuing series of reports examining life in metropolitan Milwaukee, we examined data from the last 50 years with our focus on the family. Here is some of what we found: 

* The percentage of people in Milwaukee County who have never married skyrocketed in the last 50 years. While marriage rates declined nationally, they fell more sharply here. This is true among younger, middle-aged, and older adults. 

* The decline in the marriage rate here outpaced the national trend for Black, white, and Latino adults in nearly every age bracket. 

* Average household size in the city of Milwaukee decreased dramatically in the last 50 years. Single-person households now outnumber households with at least three people. 

* In 2020, unmarried parents were more common than married ones in the city of Milwaukee. In 1970, the opposite was true. About 80% of households with kids included married parents. 

* Birth rates declined sharply. The first three years of the 2020s set successive records for the lowest number of births in the city. 

* These changes have important implications for school districts, new housing construction, and efforts to grow the city’s population to 1 million residents. 

In 1970, Milwaukee County was just completing a surge in population growth. Neighborhoods in the city and its suburbs were filled with children. 130,000 students attended Milwaukee Public Schools alone, most of them living in homes with parents who were married. 

Today, that is no longer the case. Take marriage rates, for example. To get the best detailed comparison, we examined microdata from the 1980 decennial census and from the 2017-21 American Community survey (reliable comparable microdata is unavailable in 1970). We found that the percentage of people who had never married grew sharply in Milwaukee County, far more than it did for the nation. That was true for all major racial and ethnic groups. 

We looked at “never-married” rates for people ages 45 to 54. In 1980, 9% of Black Americans had never married. By 2020, the number had climbed to 31%. But in Milwaukee County, the increase was even more dramatic. In 1980, 7% of Black Milwaukee County residents ages 45 to 54 had never married. In 2020, that number was 47%. 

In 1980, 5% of white Americans ages 45 to 54 had never married. By 2020, that number was 12%. But in Milwaukee County the never-married rate for whites 45 to 54 grew from 7% to 23%, or double the national average. 

The same trend held true for Latinos in Milwaukee County. In 1980, the national never-married rate for 45- to 54-year-old Latinos was 7%. It grew to 16% by 2020. In Milwaukee County, the non-married rate grew from 6% to 26%. 

Knowing that marriage rates have declined does not necessarily tell you anything about living situations. An unmarried person may still be living with others, whether it be a romantic partner, family, or roommates. Many people raise kids without a spouse. 

What we do know is that the average household size is shrinking — particularly in the city of Milwaukee. In 1970, 48% of Milwaukee city households included at least three members, while 30% had two, and 22% had one. 

By 2020, the share of households with at least three members had fallen from 48% to 34%. There were 113,000 households with at least three members in 1970, just 81,000 in 2020. 

In contrast, one-person households grew by 62%, from 53,000 in 1970 to 86,000 in 2020. They now constitute 36% of all households in the city. In other words, single-person households outnumber households with at least three people. 

Other data comparisons further illustrate the stunning degree of change in the city in the last 50 years. In 1970, 62% of households included a married couple. Now, 26% do. In 1970, 40% of households included children. Today, 26% have kids living in the home. And 50 years ago, married couples raising kids outnumbered unmarried parent households by nearly five to one. In 2020, unmarried parents are far more common than married ones. More than 60% of households with kids are headed by a single parent or unmarried couple. 

## There are serious implications for schools, housing

We will leave it to others to analyze what these changes mean for the health and financial well-being of families and households in Milwaukee and Milwaukee County. But one thing is certain. Families are having fewer kids. The number of babies born to Milwaukee mothers fell sharply during most of the 1990s, recovered somewhat in the early 2000s, and then plummeted again after the Great Recession of 2006. For example, there were 11,500 births in the city of Milwaukee in 2006 and 9,200 in 2019. There were fewer than 8,000 in Milwaukee last year, according to preliminary vital statistics records. The first three years of the 2020s set successive records for the fewest numbers of births in the city. 

That has serious implications for school enrollment. Birth counts are a good predictor of subsequent first grade enrollment. But Milwaukee also experiences negative domestic migration among young families. More move away from the city than to it. If current trends continue, our analysis suggests that first grade enrollment will likely be about 6,400 five years from now. That is a decline of 20% from last year’s first grade enrollment of nearly 8,000. Again, those numbers are for school enrollment in all sectors — MPS, charter and voucher. Each will be fighting for a piece of a shrinking pie. 

The changing household size in Milwaukee is also creating new housing market challenges and opportunities. During the 1970s, 80s and 90s, nearly two-thirds of new housing units were multifamily apartments. But detached single-family homes, duplexes and condominiums still made up a meaningful market share. 

In the last 15 years, the market shifted hard to multifamily construction. Through the first four years of the 2020s, nine out of 10 new units have come in multifamily developments. It’s easy to understand why, given the changing household size in Milwaukee. But all that new apartment construction still hasn’t been enough to meet demand. Remember our finding that there are now 86,000 single-person households in Milwaukee? That compares to an available supply of roughly 52,000 studio or one-bedroom apartments.  

The shrinking household size also raises a question: who will live in all those homes that were built for families decades ago? 

 And, if you’re a family in Milwaukee looking for a new, detached single-family home, you’re essentially out of luck. Property records show that only 99 were built in the city from 2020 to 2023. New condominium construction also has halted. 
 
 Finally, what do these trends, especially our declining birthrate, mean for the city’s efforts to grow its population to 1 million residents? It certainly doesn’t make reaching that goal any easier. As we’ve written, in Milwaukee’s case, growth might come from a combination of increased domestic migration and larger immigrant populations, who often have higher birth rates. 

Still, without thoughtful policy adaptation, falling birth rates and shrinking household sizes could feed a negative cycle, making Milwaukee less appealing to families. 

Falling birth rates complicate the finances of school systems that rely (partially) on per-pupil funding but maintain buildings that historically served larger student bodies. And the growth of one-person households understandably drives developers to mostly build small units. Larger, old houses are plentiful, but for those who prefer modern construction, options are slim. Because families are no longer the default kind of household, city policymakers, developers, and school officials will have to consider new ways of meeting their needs. While families now make up a minority of households, they are no less critical to the city’s future health.  

Milwaukee’s marriage and birth rates might be falling faster than the national average, but those trends are happening across the country and in virtually every wealthy nation. The status quo from 50 years ago will not return. The challenge for the next generation of local policymakers is to adapt — to foster communities that provide a high quality of life for singles, young and old alike, while also attracting and retaining families. 

(Data Note: Census tables and microdata were retrieved from the IPUMS NHGIS and IPUMS USA programs at the University of Minnesota.) 
