---
title: "In the competition for Milwaukee's neighborhoods, out-of-state landlords remain a concern"
date: "November 10, 2022"
author: "Mike Gousha and John Johnson"
---

*This article [originally appeared](https://www.jsonline.com/story/news/solutions/2022/11/10/out-of-state-landlords-remain-a-concern-for-milwaukee-neighborhoods/69627460007/) in the Milwaukee Journal Sentinel.*

This is a story about a growing competition for Milwaukee’s heart and soul: its neighborhoods. It’s a contest that pits working class residents against wealthy out-of-state investment firms in a race for the city’s most affordable houses. The Milwaukeeans' dream of becoming homeowners, of putting down roots in their community. The investors also dream of buying homes in Milwaukee but for very different reasons. They are distant landlords, often with little or no connection to the city. They see Milwaukee as a lucrative rental market, a place to make money.

We first began writing about changes to Milwaukee’s housing market several years ago.  In January of 2020, we noted a [troubling trend](https://www.jsonline.com/story/news/solutions/2020/01/30/milwaukee-homeownership-falls-sharply-massive-wealth-transfer/4590413002/) in the city.  From 2005 to 2018, owner-occupancy of homes fell sharply, from a modern day high of 80% to 68%.

Since then, Milwaukee has weathered a deadly  pandemic and witnessed homicides and opioid deaths soar to record levels.

But beneath those disheartening headlines was some encouraging news.  In the last few years, more local residents bought homes in the city.  Not to rent to someone else, but to live in.  A vote of confidence in Milwaukee’s future.

## After a decade, a rebound in owner-occupancy

New research by Marquette Law School’s Lubar Center for Public Policy Research and Civic Education shows the city began rebounding from a dramatic decade-long decline in owner-occupancy.

The number of people living in the homes they own has been rising since 2018.  There are 3,000 more owner-occupied houses in Milwaukee now than at the end of 2018.  That includes single family houses, condominiums, duplexes, and triplexes.  This wave of purchasing has caused owner-occupancy rates in the city to climb from 68% to 70%.  A small increase, but significant, nonetheless.

“The trend, if it continues, is good news for city neighborhoods and for individuals who are looking to be owner occupants,” Mayor Cavalier Johnson said.

“There are tens of thousands of people who would like to become homeowners in the city. And with these new numbers, it looks as if local homeowners are incrementally regaining ground lost over the last two decades,” he said.

Still, our analysis also reveals the acceleration of a another, more concerning development. Out-of-state investors have continued their rapid acquisition of Milwaukee homes in recent years, even as purchases by local landlords have tapered off.  Housing advocates and previous research find that the investors typically rent their properties for amounts well above what a homeowner would pay in monthly costs.

These out-of-state investors now own 7,170 single family homes, condos, duplexes or triplexes across the city, up from 5,250 at the end of 2018.  This category of ownership has grown by 50% since 2017 and 476% since 2005. 

Today, more than one in six Milwaukee rental homes is owned by a landlord based outside Wisconsin.

The outcome of the growing competition between working-class residents and out-of-state investment companies has long-term implications for Milwaukee, affecting the pool of affordable houses available in the city, housing costs, wealth creation, and neighborhood stability and social cohesion.

In short, the stakes are high, with hopeful homebuyers also facing new pressures from rising interest rates and an uncertain economic outlook.

## 'I wanted to be in this neighborhood'

Forty-four-year-old Tommy Kirk is one of the 3,000 new homeowners in Milwaukee since 2018.  In May, Kirk bought an $85,000 four-bedroom bungalow on 30th Street south of Hampton.  Quiet and tree-lined, the block features homes that are still mostly owner-occupied.

“I wanted to be in this neighborhood,” Kirk told us during a recent visit to his home. “I’ve got roots in this neighborhood.”

Kirk had grown weary of his former two-bedroom apartment in what he called a “not so peaceful” area on the west side.  With a wry smile, he said he had become “a landlord in training” because he had to do basic maintenance and repairs on the unit that his landlord refused to do.

Still, buying a home wasn’t easy.

“It was always a dream, but I had a bunch of hurdles,” he said.

For the last two years, Kirk has been center manager for the Repairers of the Breach shelter for homeless adults at 13th and Vliet.  But sitting on the couch he had just purchased for his new home, Kirk talked candidly about the struggles in his early years, both legal and financial.

To qualify for home ownership, Kirk worked with the non-profit Acts Housing for two years, which helped him resolve his financial issues and prepare him for buying a home.  He received assistance with a down payment from various grant sources, including his mortgage provider, Johnson Bank, and a state housing program.  Financial assistance is often necessary because of the city’s racial wealth gap and housing rehab costs.  It’s proven to be a good investment.  Acts itself has made more than $5 million in mortgage loans since 2013. Only $30,000 of that total have been charge-offs, where repayment is questionable.

Today, Kirk is paying $720 a month for his mortgage, taxes, and insurance.  Comparable homes will often rent for hundreds of dollars more. What seemed impossible decades ago is now a reality.

“I said to anybody and everybody, it’s possible for me and for anyone to set a goal,” Kirk told us.

## An uptick in each of the city's aldermanic districts

Tommy Kirk’s home purchase was one of 800 facilitated by Acts Housing in Milwaukee over the last four years.  Our research suggests that its work and that of other non-profit organizations, the city of Milwaukee, and Milwaukee County are making a difference.

Owner-occupancy has increased in each of the city’s 15 aldermanic districts. The largest increase in the number of owner-occupied houses occurred in the 10th and 5th districts, on the far west and far northwest sides of the city.  Compared to 2018, there are now 350 more owner-occupants in the 5th district.  There are 280 additional owner-occupants in the 10th.

At the neighborhood level, 13 neighborhoods saw at least another 5% of their total housing stock become owner-occupied. They include Murray Hill and Riverside Park on the east side, Southgate on the south side, Martin Drive and Miller Valley on the near west side, Lenox Heights on the west side, and Florist Highlands on the far northwest side.

Homeownership grew the least on the near south side.

No neighborhood of at least 100 houses saw more than a 4% decline in owner occupancy. Only three neighborhoods saw a double-digit decrease in the number of owner-occupied parcels. The biggest was in Franklin Heights, the neighborhood surrounding the former A.O. Smith plant south of 27th and Capitol, where there were about 40 fewer owner-occupants.

But just as the number of owner-occupants has increased in the city, so has the number of purchases made by out-of-state real estate investment companies.  Our analysis shows that the investors have almost exclusively targeted majority-Black neighborhoods, with the growth concentrated in a third of the city’s 15 aldermanic districts.  All are on the north side.

In the 7th district, 1,100 houses are owned by an out-of-state landlord, an increase of 450 since 2018.

In the adjacent 1st district, 1,080 houses are owned by an out-of-state landlord, an increase of 440 since 2018.

Out-of-state landlords also own more than 700 homes in each of the 2nd, 15th, and 6th districts.

Across these five districts combined, more than 4,500 houses are now owned by out-of-state investors, a 62% increase since 2018.

Put another way, an additional 1,900 homes in majority Black neighborhoods are now owned by companies with business headquarters outside Wisconsin.

That trend simply hasn’t happened in majority white neighborhoods, where the number of houses owned by out-of-state landlords fell by nearly 100.  Majority Hispanic neighborhoods have seen relatively little activity by these investors.

In neighborhoods like St. Joseph and Harambee, the pace of out-of-state investment and home ownership is closely matched.  Out-of-state investors are in the lead in Sherman Park, Uptown, Silver Spring, and Old North Milwaukee. In contrast, homebuyers in Riverwest, Jackson Park, Bay View, and Washington Heights have faced relatively little competition from outside investors.

Three companies now account for 20% of all out-of-state owned rental properties.  In 2018, they owned just 2%.  Collectively, VineBrook Homes of Dayton, Ohio, Highgrove Holdings of Torrance, Calif., and SFR3 of Mill Valley, Calif., owned more than 1,400 houses as of mid-2022.  They owned just 83 at the end of 2018.

All three of these private equity-backed companies were profiled in the spring of 2021 by the Lubar Center and Milwaukee Journal Sentinel.  Since then, they’ve rapidly expanded their portfolios.

SFR3 and VineBrook largely purchase single family homes to be used as rentals.  The typical value of the home is about $100,000. The most current available data shows VineBrook owns 908 homes in Milwaukee. SFR3 owns 255. Nearly all VineBrook and SFR3 properties are north of Capitol Drive and west of N. 35th Street.

Highgrove’s investments follow a different profile.  It buys mostly duplexes with a median value of $50,000. The California firm now owns 279 properties in Milwaukee.  Highgrove’s properties mostly fall within the near north side: south of Capitol, east of Sherman Boulevard, and west of Holton Street.

While encouraged by the increase in owner-occupancy in his city,  Johnson is concerned about the growing number of properties now in the hands of out-of-state investors.

“Out-of-state investors are far less likely to care about a neighborhood,” the mayor said. “They are less likely to get involved in civic life.

“I want neighborhoods to have stability, and transient renters don’t offer the same stability that homeowners provide. When neighbors have a sense of permanence, when they know each other, and when they care about the neighborhood’s future, that makes the entire city stronger and safer,” Johnson said.

On their websites, the large out-of-state investors say that they are meeting an existing need for quality, affordable rental options and providing needed investment in aging houses.  Some renters may not want to buy but still want to live in a single-family home or duplex.  Others don’t have the money for a down payment.

But as our previous reporting suggests, investment in cities such as Milwaukee is also highly profitable. That attracts private investors, which allows the larger firms to mostly pay cash for their purchases.  An increasing number are bulk purchases of multiple properties all at once.

As the Milwaukee housing market got hotter and hotter, housing prices continued to climb. Zillow’s Home Value index placed the typical Milwaukee home at $127,000 in June of 2019.  It was $183,000 in June of 2022, an increase of 44% over three years.

Recent increases in housing prices have dramatically reduced the pool of low-priced houses in Milwaukee.  In 2018, half of all houses were assessed below $100,000. Today, 30% are. The pool of homes worth less than $50,000 is almost gone.

In a housing market where cash, speed, and scale are king, residents of more modest means are at a distinct disadvantage.

“I like to think of them (out-of-state investors) as one of the new barriers to home ownership” Acts Housing senior vice president of real estate Dorothy York said.

Acts president and CEO Michael Gosman said the new market dynamics make the dream of purchasing a home less attainable.

“We have families that lost out to investors even when investors were paying less,” he said.

## A key cog in Milwaukee's affordable housing plan

To compete with the large out-of-state investment firms, the non-profit recently announced the creation of the Acts Homeowner Acquisition Fund.  The ambitious $11 million program was formed with the support of the Community Development Alliance and is a key part of Milwaukee’s Collective Affordable Housing plan. To date, Acts has raised $3 million of its $11 million goal.  It has grant requests pending with both the city and county.

Acts said the fund will allow it to create an expanded inventory of homes in the $90,000 to $140,000 range with monthly ownership costs of $900 to $1,200.

York will lead the effort to identify ownership opportunities.  She said the fund will help level the playing field as the non-profit competes with out-of-state investors for available properties in the city.

“We can compete with them on their own terms,” York said.

The competition between local and out-of-state interests is producing an all-hands-on-deck approach in the city, with government, non-profits, businesses, and philanthropies working together to address affordable housing issues.

Community Development Alliance chief executive Teig Whaley-Smith said that nationally, there are at least two strategies used to mitigate what he calls “the negative impact of predatory acquisition of single-family homes and duplexes.”

The first is requiring that landlords offer properties to tenants before selling to other landlords. The second is using landlord licensing to discourage negligent landlords.  But in 2017, the Wisconsin Legislature passed a law that prohibits the city from requiring landlord licensing. 

The local efforts to reduce the impact of out-of-state investors also face another, newer obstacle.  In the early 2010s, real estate investors commonly bought properties from distressed homeowners. In contrast, our latest research found that the new breed of private equity investors often acquires its properties from local and suburban landlords, whose numbers are now declining. Increasingly, these houses are sold in package deals and often for cash.

In 2022 alone, VineBrook has spent nearly $20 million buying 176 properties in 27 different bulk purchases, mostly from smaller, Wisconsin-based landlords.  Some sales were large, like a 17-property $1.65 million deal with a Muskego-based landlord in May.  Others were small, like a $194,000 purchase of two properties from a Milwaukee-based company in January.  None required financing.

This kind of sale completely excludes hopeful homebuyers in the market, even though residents in these neighborhoods, most of them majority Black, could often afford the houses if they were priced individually.

## A persistent racial gap in mortgage recipients

The dynamics of the market contribute to an enormous racial gap between mortgage recipients in Milwaukee.  Although the white and Black adult populations of the city are roughly equal, our research found that white mortgage recipients outnumbered Black mortgage recipients by a two-to-one margin. Still, that was progress from 2018, when the gap between white and Black recipients was more than three-and-a-half to one.

Whaley-Smith said it’s important for the city to look at what’s happening through a racial equity lens.  He said it’s no surprise that families are choosing Milwaukee to buy a home but said the owner-occupancy growth is still unequal.

“Increased white home ownership is driving the overall growth, and although there have been hundreds of new homeowners of color, this growth has been wiped out by the predatory acquisition that is taking single family homes and duplexes off the market,” Whaley-Smith said.

Johnson echoed that concern.

“Homeownership is key to building generational wealth in this country, and I don’t want any Milwaukeean’s potential to build a better life for themselves and their family to be limited because of how hard it can be to buy a house when they’re ready for homeownership,” he said.

As interest rates rise, the impact on the struggle for Milwaukee’s heart and soul − its neighborhoods − is unclear. Historically low mortgage interest rates played a role in increased owner occupancy.  Those rates are now less attractive for a working-class buyer. The private equity firms can pay in cash.  Will that tip the balance in some neighborhoods, where both trends have been playing out?

What is clear is that the competition between local buyers and out-of-state investors is real, urgent, and far from over.  In the last 19 months, two of the houses on the block where Tommy Kirk now lives were purchased by an out-of-state investor.
